### ISSUE TITLE
Cannot read property 'hash' of undefined

### ISSUE THREAD

**Issue by caicaishmily** [howtographql/graphql-js#41] opened 2018-07-24 14:14 UTC
I'm trying to test signup using the playground When I read the Authentication, After I followed the tutorial step by step. but  I got an Cannot read property 'hash' of undefined error
Here are the screenshots:
![image](https://user-images.githubusercontent.com/19269210/43143941-95420e62-8f8e-11e8-9130-ad374c4e58e5.png)

May be checkout new branch every chapter for example is better

**Comment by caicaishmily** [comment] 2018-07-24 14:21
When I run this, It's give me another eror:
```js
mutation {
  post(
    url: "www.graphql-europe.org"
    description: "Europe's biggest GraphQL conference"
  ) {
    id
  }
}
```

![image](https://user-images.githubusercontent.com/19269210/43144396-a00cdc2c-8f8f-11e8-9851-0bd41839f24d.png)

**Comment by itscarlosrufo** [comment] 2019-02-04 13:19
Thanks @caicaishmily for opening this issue 😄. I cannot reproduce the use case that you've mentioned, probably it'd be related to an not updated server instance or even an server error. I've just tried and it works well for me. Closing this for now, please, feel free to open an issue if you cannot make it work!

**Closed as completed by itscarlosrufo** 2019-02-04 13:19 UTC
