### ISSUE TITLE
Sorting does not work correctly on feed, when feed-resolver gets links after query-resolver

### ISSUE THREAD

**Issue by wanradt** [howtographql/graphql-js#46] opened 2018-11-06 00:34 UTC
In `links`-resolver (https://github.com/howtographql/graphql-js/blob/master/src/resolvers/Feed.js) we get links by IDs, but this changes order back to natural (by IDs?), so sorting one step before in `feed`-function (`Qurey.js`) is now gone. 

How to implement it without losing sorting?

**Comment by itscarlosrufo** [comment] 2019-02-04 13:16
Thanks @wanradt for opening this issue 😄. The attached link is broken, also I cannot reproduce it. Closing this for now, please, feel free to open an issue if you cannot make it work!

**Closed as completed by itscarlosrufo** 2019-02-04 13:16 UTC
